remote_theme: jekyll/minima
markdown: kramdown

# Site settings
title: wmWebStack - HTTP Server Stack for Windows - Apache, PHP & MySQL
description: >- 
  wmWebStack is a lightweight, installable HTTP server for Windows with all required server stacks. Easy live publishing in one click.

url: "https://webstack.wikimint.com" 
baseurl: "" 


# Ensure Jekyll includes the docs folder
include:
  - docs

include_homepage: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
